[package]
name = "cborlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
ciborium = "0.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "cbor_bench"
harness = false

[profile.release]
opt-level = 3
lto = true
